
var googleSr={maxAds:{'head':2,'mid':1,'foot':3},maxNumberOfAds:6,headers:{'head':'<div id="gad_sr_header"><span style="float:right"><a class="sponsored_plain" target="_google" href="http://services.google.com/feedback/online_hws_feedback">Sponsored Links</a></span>','mid':'<div class="box mark sponsored-box"><div class="image"><a target="google_ad" href="~ad-link~"><img width="214" height="112" src="/i/google_ad_image_wide.png" /></a></div><div class="text-block"><div class="sponsored"><a target="_google" href="http://services.google.com/feedback/online_hws_feedback">Sponsored Link</a></div>','foot':'<div class="googlead container"><p class="sponsored"><a target="_google" href="http://services.google.com/feedback/online_hws_feedback">Sponsored Links</a></p><ul>'},footers:{'head':'</div>','mid':'</div></div>','foot':'</ul></div>'},ads:{'head':new Array(),'mid':new Array(),'foot':new Array()},seenAds:{'head':0,'mid':0,'foot':0},adStore:new Array(),hasAds:function(section){return(this.ads[section].length>0);},addAd:function(ad,section){if(typeof ad!='undefined')
{ad.line2=ad.line2.replace(/<(.{0,1})b>/g,'');ad.line1=ad.line1.replace(/<(.{0,1})b>/g,'');this.ads[section].push(ad);}
this.seenAds[section]++;},getAdHtml:function(section,ad){if(section=='head')
{if(this.topTrial)
{return'<li><p class="heading"><a target="google_ad" href="'+ad.url+'">'+ad.line1+'</a></p><span class="text">'+ad.line2+'</span> - <a target="google_ad" href="'+ad.url+'">'+ad.visible_url+'</a></li>';}
else
{return'<a target="google_ad" href="'+ad.url+'" class="title_link">'+ad.line1+'</a><br /><br /><p class="text">'+ad.line2+' - <a target="google_ad" href="'+ad.url+'">'+ad.visible_url+'</a></p>';}}
else if(section=='mid')
{return'<h2><a target="google_ad" href="'+ad.url+'">'+ad.line1+'</a></h2><p class="text">'+ad.line2+'</p><a target="google_ad" href="'+ad.url+'">'+ad.visible_url+'</a>';}
else if(section=='foot')
{return'<li><p class="heading"><a target="google_ad" href="'+ad.url+'">'+ad.line1+'</a></p><span class="text">'+ad.line2+'</span> - <a target="google_ad" href="'+ad.url+'">'+ad.visible_url+'</a></li>';}},setTopTrial:function(){this.topTrial=true;this.headers['head']=this.headers['foot'];this.footers['head']=this.footers['foot'];},getHeader:function(section){return this.headers[section];},getFooter:function(section){return this.footers[section];},hasSlotsAvailable:function(section){return this.seenAds[section]<this.maxAds[section];},writeAds:function(section){if(section=='mid')
{var hdr=this.getHeader(section);var midAd=this.ads[section][0];hdr=hdr.replace(/~ad-link~/,midAd.url);document.write(hdr);}
else
{document.write(this.getHeader(section));}
this.adHtmlWrap(section);document.write(this.ads[section].join('<br />'));document.write(this.getFooter(section));},adHtmlWrap:function(section){for(var i=0;i<this.ads[section].length;i++)
{this.ads[section][i]=this.getAdHtml(section,this.ads[section][i]);}},addToStore:function(ad){this.adStore.push(ad);},moveAdFromStore:function(targetSection){this.addAd(this.adStore.pop(),targetSection);},hasAdsInStore:function(){return(this.adStore.length>0);},acceptGoogleAds:function(ads){this.tempStore=ads.reverse();for(var i=0;i<this.tempStore.length;i++)
{this.tempStore[i].line2=this.tempStore[i].line2+' '+this.tempStore[i].line3;delete this.tempStore[i].line3;this.addToStore(this.tempStore[i]);}},getMaxNumberOfAds:function(){return this.maxNumberOfAds;}};